server:
    image: rancher/server:v0.47.0-rc2
    restart: always
    ports:
        - 8080:8080
    environment:
        JAVA_OPTS: '-Xmx4096m'
    volumes:
        - /etc/localtime:/etc/localtime:ro
    volumes_from:
        - rancher-data
# following works only with docker-compose 1.5 or newer
#    log_driver: "gelf"
#    log_opt:
#       address: "udp://swarm01-eeasites.eea.europa.eu:12201"
