#
# Requires docker-compose 1.7
#


nginx:
    restart: always
    image: nginx:1.8.1
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./html:/usr/share/nginx/html:ro
        - ./nginx/tls:/etc/nginx/tls:ro
    links:
        - server

#
# Rancher server
#
server:
    image: rancher/server:v1.1.0
    restart: always
    environment:
        - JAVA_OPTS=-Xmx4096m
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - rancher-mysql-data:/var/lib/mysql
        - rancher-cattle-data:/var/lib/cattle
        - rancher-mysql-logs:/var/log/mysql

mysql-backup:
    image: deitch/mysql-backup:0.7.0
    restart: always
    environment:
        - DB_DUMP_FREQ=1440
        - DB_DUMP_BEGIN=2330
        - DB_DUMP_TARGET=/db
    links:
        - server:db
    volumes:
        - ./mysql-backup:/db

# TOADD enable logging to graylog
# following works only with docker-compose 1.5 or newer
#    log_driver: "gelf"
#    log_opt:
#       address: "udp://swarm01-eeasites.eea.europa.eu:12201"

#dbservice:
#    image: mysql:5.5.50
#    restart: always
#    environment:
#        - MYSQL_ROOT_PASSWORD=forgedaboutit
#    command:
#        - mysqld
#        - --key_buffer_size=16M
#        - --max_allowed_packet=16M
#        - --max_connections=1000
#        - --sql_mode=ONLY_FULL_GROUP_BY
#        - --query_cache_limit=1M
#        - --query_cache_size=16M
#        - --innodb_buffer_pool_size=2GB
#    volumes:
#        - rancher-mysql-data:/var/lib/mysql

