nginx:
    restart: always
    image: nginx:1.8.1
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./html:/usr/share/nginx/html:ro
        - ./nginx/tls:/etc/nginx/tls:ro
    links:
        - server

server:
    image: rancher/server:v1.0.0
    restart: always
    environment:
        - JAVA_OPTS=-Xmx4096m
    volumes:
        - /etc/localtime:/etc/localtime:ro
    volumes_from:
        - rancher-data

rancher-data:
    image: busybox
    volumes:
       - /var/lib/mysql

mysql-backup:
    image: deitch/mysql-backup:0.7.0
    restart: always
    environment:
        - DB_DUMP_FREQ=360
        - DB_DUMP_BEGIN=+0
        - DB_DUMP_TARGET=/db
    links:
        - server:db
    volumes:
        - ./mysql-backup:/db

# TOADD enable logging to graylog
# following works only with docker-compose 1.5 or newer
#    log_driver: "gelf"
#    log_opt:
#       address: "udp://swarm01-eeasites.eea.europa.eu:12201"

