#nginx:
# to add nginx proxy with ssl termination

server:
    image: rancher/server:v1.0.0
    restart: always
    ports:
        - "8080:8080"
    environment:
        - JAVA_OPTS=-Xmx4096m
    volumes:
        - /etc/localtime:/etc/localtime:ro
    volumes_from:
        - rancher-data

rancher-data:
    image: busybox
    volumes:
       - /var/lib/mysql

# MYSQL backup service
#
# docker run -d --restart=always -e DB_DUMP_FREQ=2 -e DB_DUMP_BEGIN=+0 -e DB_DUMP_TARGET=/db -e DB_DUMP_DEBUG=true \ 
#    --link eeadockerrancher_server_1:db -v /var/local/deploy/mysql-backup:/db deitch/mysql-backup 

# following works only with docker-compose 1.5 or newer
#    log_driver: "gelf"
#    log_opt:
#       address: "udp://swarm01-eeasites.eea.europa.eu:12201"
